# Generated by Django 5.1.1 on 2024-10-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_pdfupload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdfupload",
            old_name="pdf_file",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="pdfupload",
            name="user",
        ),
    ]
